#!/bin/sh

hint="Please start connman service first!"

wait_connman()
{
	connmanctl technologies 2>&1 | grep "was not provided" > /dev/null
	if [ $? -eq 0 ]; then
		echo $hint
		exit 1
	fi
}

ap_start()
{
	wait_connman

	echo "Starting SoftAP!"
	connmanctl tether wifi on
}

ap_stop()
{
	wait_connman

	echo "Stopping SoftAP!"
	connmanctl tether wifi off
}

check_status()
{
	connmanctl technologies 2>&1 | \
		sed '1,/Type = wifi/d' | \
		grep Tethering | \
		head -n 1 | \
		awk '{ print $3 }'
}

case "$1" in
start)
	ap_start
	;;

stop)
	ap_stop
	;;

status)
        echo "AP mode = `check_status`"
        ;;
toggle)
	case `check_status` in
		False)
		ap_start
		;;
		True)
		ap_stop
		;;
		*)
		echo $hint
	esac
	;;

*)
	echo "Usage: $0 start|stop|toggle"
	echo "  start  - Start AP mode"
	echo "  stop   - AP mode is stopped and we return to station mode"
        echo "  status - Show current AP mode status"
	echo "  toggle - Start or stop AP mode depending on previous mode."
	echo ""
	;;
esac
